### ISSUE TITLE
Issue with the last snaphsot org.openmrs.module.initializer.api.form.BahmniFormsLoader class not found

### ISSUE THREAD

**Issue by deniger** [mekomsolutions/openmrs-module-initializer#61]
Hello,
we have an issue with the last version of openmrs-module-initializer.
Shall we add a new import in our distribution ?
```
Caused by: java.lang.IllegalStateException: Failed to introspect bean class [org.openmrs.module.initializer.api.form.BahmniFormsLoader] for persistence metadata: could not find class that it depends on
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:396)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(PersistenceAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:923)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: Lorg/bahmni/module/bahmni/ie/apps/service/BahmniFormService;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.buildPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:411)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:392)
	... 17 more
```

**Comment by mks-d** [comment]
Thanks @deniger for reporting this.
I think [this](https://github.com/mekomsolutions/openmrs-module-initializer/commit/0455f2e00ad64f2d9c482ed7556db1aae1831757#diff-0f864fd16d5618b5b560f5ee51705a07R27) is the issue, we are investigating...

**Comment by mks-d** [comment]
@deniger [this change](https://github.com/mekomsolutions/openmrs-module-initializer/commit/d2b2bd5ad091d06a1d2d2dce29fb9d13842a091b#diff-0f864fd16d5618b5b560f5ee51705a07L27) should make the problem go away, can you confirm?

Cc @chinzou
